version: '3'

services:
  nginx:
    build: .
    ports:
      - 1338:80
    networks:
      ikerocio_network:
    restart: on-failure
networks:
  ikerocio_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
