services:
  nextjs_ikerocio:
    build:
      context: .
      dockerfile: ./compose/local/nextjs/Dockerfile
    image: ikerocio_local_nextjs
    container_name: nextjs_ikerocio
    volumes:
      - .:/app:z
    environment:
      # nextjs
      - "USE_DOCKER=yes"
    ports:
      - "5000:5000"
    command: /start
