services:
  nextjs_ikerocio:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: ikerocio_local_nextjs
    container_name: nextjs_ikerocio
    volumes:
      - ./ikerocio:/app:z
    environment:
      # nextjs
      - "USE_DOCKER=yes"
    ports:
      - "3000:3000"
