version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django_ikerocio:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ikerocio_local_django
    container_name: django_ikerocio
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    environment:
      # postgres
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DB=prueba_1'
      - 'POSTGRES_USER=debug'
      - 'POSTGRES_PASSWORD=debug'
      # django
      - 'USE_DOCKER=yes'
      - 'IPYTHONDIR=/app/.ipython'
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DB=prueba_1'
      - 'POSTGRES_USER=debug'
      - 'POSTGRES_PASSWORD=debug'
