version: '3'

networks:
  default:
    external:
      name: ikerocio_network

volumes:
  ikerocio_postgres_data: {}
  ikerocio_postgres_data_backups: {}
  data_mysql: {}

services:
  ikerocio:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ikerocio_production_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - 'DJANGO_ALLOWED_HOSTS=.ikerocio.com,www.ikerocio.com,localhost'
    command: /start
    restart: unless-stopped
    networks:
      default:
  
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ikerocio_production_postgres
    volumes:
      - ikerocio_postgres_data:/var/lib/postgresql/data:Z
      - ikerocio_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped
    networks:
      default:
  
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: ikerocio_production_nginx
    depends_on:
      - django
    volumes:
      - ./ikerocio/static:/staticfiles
    ports:
      - "80"
    restart: unless-stopped
    volumes:
      - ./compose/production/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      default: