networks:
  default:
    name: ikerocio_network

services:
  nextjs_ikerocio:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: iocio005/ikerocio_prod_nextjs:latest
    container_name: ikerocio_prod_nextjs
    environment:
      # nextjs
      - "USE_DOCKER=yes"
    ports:
      - "8080:3000"
