version: '3'
networks:
  default:
    name: ikerocio_network
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.8.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
      - MARIADB_ROOT_PASSWORD=itdCZfcHQb57zJiuTTyUXRMCM0jxtWD7jhjsO
      - MARIADB_PASSWORD=itdCZfcHQb57zJiuTTyUXRMCM0jxtWD7jhjsO
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  ghost:
    image: docker.io/bitnami/ghost:latest
    ports:
      - '2368:2368'
    volumes:
      - 'ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb
    environment:
      - GHOST_BLOG_TITLE=ikerocio.com
      - GHOST_HOST=blog.ikerocio.com
      - GHOST_DATABASE_PASSWORD=itdCZfcHQb57zJiuTTyUXRMCM0jxtWD7jhjsO
      - GHOST_DATABASE_HOST=mariadb
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - GHOST_ENABLE_HTTPS=yes
    restart: unless-stopped
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
