name: Deploy to Server
on:
  push:
    branches:
      - migration/nextjs
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:23.0-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Compose
        run: |
          docker-compose -f production.yml build
          docker-compose -f production.yml push
